properties:


  - name: filename
    type: std::string
    init_with: '"filename-not-set.tmj"'
    constructor_arg: true

  - name: num_columns
    type: int
    init_with: 0
    getter: explicit

  - name: num_rows
    type: int
    init_with: 0
    getter: explicit

  - name: tile_width
    type: int
    init_with: 0
    getter: explicit

  - name: tile_height
    type: int
    init_with: 0
    getter: explicit

  - name: loaded
    type: bool
    init_with: false
    getter: true


functions:


  - name: load
    body: |
      return;


  - name: get_num_columns
    type: int
    guards: [ loaded ]
    body: return num_columns;


  - name: get_num_rows
    type: int
    guards: [ loaded ]
    body: return num_rows;


  - name: get_tile_width
    type: int
    guards: [ loaded ]
    body: return tile_width;


  - name: get_tile_height
    type: int
    guards: [ loaded ]
    body: return tile_height;


dependencies:


  - symbol: nlohmann::json
    headers: [ lib/nlohmann/json.hpp ]


