properties:


  - name: filename
    type: std::string
    init_with: '"filename-not-set.tmj"'
    constructor_arg: true

  - name: num_columns
    type: int
    init_with: 0

  - name: num_rows
    type: int
    init_with: 0

  - name: tile_width
    type: int
    init_with: 0

  - name: tile_height
    type: int
    init_with: 0

  - name: loaded
    type: bool
    init_with: false


functions:


  - name: load
    type: bool
    guards: [ (!loaded) ]
    body: |
      if (!TheWeepingHouse::FileExistenceChecker(filename).exists())
      {
         std::cout << "[TheWeepingHouse::ConfigurationTMJLoader::load]: ERROR: "
                   << "Trying to load the file \"" << filename << "\" but it does not exist."
                   << std::endl;
      }

      // load and validate the json data to variables
      std::ifstream i(filename);
      nlohmann::json j;
      try
      {
         i >> j;
      }
      catch (const std::exception& e)
      {
         i.close();
         std::stringstream error_message;
         error_message << "[ConfigurationTMJLoader::load]: ERROR: the file \"" << filename << "\" appears to have"
                       << " malformed JSON. The following error was thrown by nlohmann::json: \""
                       << e.what() << "\"";
         throw std::runtime_error(error_message.str());
      }

      num_columns = j["width"]; // get width
      num_rows = j["height"]; // get height
      tile_width = j["tilewidth"]; // get width
      tile_height = j["tileheight"]; // get height


      loaded = true;

      return true;
    body_dependency_symbols:
      - std::cout
      - std::ifstream
      - nlohmann::json
      - TheWeepingHouse::FileExistenceChecker


  - name: get_num_columns
    type: int
    guards: [ loaded ]
    body: |
      return num_columns;


  - name: get_num_rows
    type: int
    guards: [ loaded ]
    body: |
      return num_rows;


  - name: get_tile_width
    type: int
    guards: [ loaded ]
    body: |
      return tile_width;


  - name: get_tile_height
    type: int
    guards: [ loaded ]
    body: |
      return tile_height;



dependencies:


  - symbol: std::ifstream
    headers: [ fstream ]
  - symbol: nlohmann::json
    headers: [ lib/nlohmann/json.hpp ]
  - symbol: TheWeepingHouse::FileExistenceChecker
    headers: [ TheWeepingHouse/FileExistenceChecker.hpp ]


