properties:


  - name: bitmap_bin
    type: AllegroFlare::BitmapBin*
    init_with: nullptr
    constructor_arg: true
    setter: false

  - name: font_bin
    type: AllegroFlare::FontBin*
    init_with: nullptr
    constructor_arg: true
    setter: false

  - name: event_emitter
    type: AllegroFlare::EventEmitter*
    init_with: nullptr
    constructor_arg: true
    setter: false

  - name: entity_collection_helper__this_is_a_hack
    type: AllegroFlare::Prototypes::FixedRoom2D::EntityCollectionHelper*
    init_with: nullptr
    constructor_arg: true
    setter: false

  - name: result_configuration
    type: AllegroFlare::Prototypes::FixedRoom2D::Configuration
    init_with: ''
    getter: explicit
    setter: false

  - name: built
    type: bool
    init_with: false

  - name: inventory_index
    type: AllegroFlare::InventoryIndex&
    init_with: result_configuration.get_inventory_index_ref()

  - name: af_inventory
    type: AllegroFlare::Inventory&
    init_with: result_configuration.get_af_inventory_ref()

  - name: flags
    type: AllegroFlare::Inventory&
    init_with: result_configuration.get_flags_ref()

  - name: entity_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Entities::Base*>&
    init_with: result_configuration.get_entity_dictionary_ref()

  - name: room_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Room*>&
    init_with: result_configuration.get_room_dictionary_ref()

  - name: entity_room_associations
    type: std::map<std::string, std::string>&
    init_with: result_configuration.get_entity_room_associations_ref()

  - name: script_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Script>&
    init_with: result_configuration.get_script_dictionary_ref()

  - name: starting_in_room_identifier
    type: std::string
    init_with: result_configuration.get_starting_in_room_identifier_ref()


functions:


  - name: get_result_configuration
    type: AllegroFlare::Prototypes::FixedRoom2D::Configuration
    guards: [ built ]
    body: |
      return result_configuration;


  - name: build
    type: AllegroFlare::Prototypes::FixedRoom2D::Configuration
    guards: [ bitmap_bin, font_bin, event_emitter, entity_collection_helper__this_is_a_hack ]
    body: |
      if (built) return result_configuration;
      built = true;



      const std::string FRONT_PATIO = "front_patio";
      const std::string FRONT_HALLWAY = "front_hallway";
      const std::string MAIN_HALLWAY = "main_hallway";
      const std::string FIRST_FLOOR_STORAGE_ROOM = "first_floor_storage_room";
      const std::string BACK_PORCH = "back_porch";

      const std::string FRONT_PATIO_DOOR = "front_patio_door";

      AllegroFlare::Prototypes::FixedRoom2D::Configuration &result = result_configuration;



      TheWeepingHouse::EntityFactory entity_factory(bitmap_bin);
      entity_factory.set_hide_hitspots(true);

      AllegroFlare::Prototypes::FixedRoom2D::RoomFactory room_factory(
         bitmap_bin, font_bin, event_emitter, entity_collection_helper__this_is_a_hack
      );

      inventory_index = AllegroFlare::InventoryIndex::build_placeholder_inventory_index();

      af_inventory.add_item(1);
      af_inventory.add_item(4);
      af_inventory.add_item(3);

      room_dictionary = {
         { FRONT_PATIO, room_factory.create_room() },
         { FRONT_HALLWAY, room_factory.create_room() },
         { MAIN_HALLWAY, room_factory.create_room() },
         { FIRST_FLOOR_STORAGE_ROOM, room_factory.create_room() },
         { BACK_PORCH, room_factory.create_room() },
      };

      entity_dictionary = {
         { "front_patio_bg", entity_factory.create_background("room_2.png", "observe_front_patio") },
         { "front_hallway_bg", entity_factory.create_background("room_0.png", "observe_front_hallway") },
         { "main_hallway_bg", entity_factory.create_background("room_1.png", "observe_main_hallway") },
         { "first_floor_storage_room_bg", entity_factory.create_background("room_3.png", "observe_first_floor_storage_room") },
         { "back_porch_bg", entity_factory.create_background("room_4.png", "observe_back_porch") },

         { "door1", entity_factory.create_rectangle_hitspot(1725, 440, 60, 350, "Door 1", "observe_door1") },
         { "door2", entity_factory.create_rectangle_hitspot(115, 440, 60, 350, "Door 2", "observe_door2") },
         { FRONT_PATIO_DOOR, entity_factory.create_rectangle_hitspot(1725, 440, 60, 350, "Door 2", "observe_front_patio_door") },
         { "wall_art", entity_factory.create_ellipse_hitspot(1150, 450, 60, 60, "Wall Art", "observe_wall_art") },
      };

      entity_room_associations = {
         { "front_patio_bg", FRONT_PATIO },
         { FRONT_PATIO_DOOR, FRONT_PATIO },

         { "front_hallway_bg", FRONT_HALLWAY },
         { "door1", FRONT_HALLWAY },
         { "wall_art", FRONT_HALLWAY },

         { "main_hallway_bg", MAIN_HALLWAY },
         { "door2", MAIN_HALLWAY },

         { "first_floor_storage_room_bg", FIRST_FLOOR_STORAGE_ROOM },

         { "back_porch_bg", BACK_PORCH },
      };


      script_dictionary = {
         { "observe_front_patio", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: What a nice place... but it doesn't look very invnting.  I'd better see if I can get inside."
         })},
         { "observe_front_hallway", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: This is a pretty dark room. | It's kinda hard to see anything, to be honest."
         })},
         { "observe_main_hallway", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: This is a pretty dark room. | It's kinda hard to see anything, to be honest."
         })},
         { "observe_first_floor_storage_room", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: A little storage room.  Looks like some boxes are in here."
         })},
         { "observe_back_porch", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: It sure is nice to have a place out of the rain for now."
         })},


         { "observe_front_patio_door", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: Oh wow, it's unlocked.  I'm going inside.",
               "ENTER_ROOM: " + FRONT_HALLWAY,
         })},
         { "observe_door1", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: Just a regular door. | I'm going to step through it.",
               "ENTER_ROOM: " + MAIN_HALLWAY,
         })},
         { "observe_door2", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: A regular door. | I'll go in.",
               "ENTER_ROOM: " + FRONT_HALLWAY,
         })},
         { "collect_keys", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "COLLECT: keys"
         })},
         { "observe_wall_art", AllegroFlare::Prototypes::FixedRoom2D::Script({
               "DIALOG: That's some interesting art on the wall.  I wonder what it's for.",
         })},
      };

      //const std::string FRONT_PATIO = "front_patio";
      //const std::string FRONT_HALLWAY = "front_hall";
      //const std::string MAIN_HALLWAY = "main_hallway";
      //const std::string FIRST_FLOOR_STORAGE_ROOM = "first_floor_storage_room";
      //const std::string BACK_PORCH = "back_porch";
      starting_in_room_identifier = FRONT_PATIO;
       
      built = true;

      return result;
    body_dependency_symbols:
      - TheWeepingHouse::EntityFactory
      - AllegroFlare::Prototypes::FixedRoom2D::RoomFactory


  - name: assemble_room
    type: bool
    parameters:
      - name: name
        type: std::string
        default_argument: '"[unset-name]"'
      - name: background_bitmap_identifier
        type: std::string
        default_argument: '"[unset-background_bitmap_identifier]"'
      - name: observe_script_text
        type: std::string
        default_argument: '"[unset-background_bitmap_identifier]"'
    body: |
      // TODO this function
      // TODO check if it already exists
      //room_dictionary[FRONT_PATIO] = room_factory.create_room();
      
      return true;


  - name: room_exists
    type: bool
    parameters:
      - name: name
        type: std::string
        default_argument: '"[unset-name]"'
    body: |
      // TODO
      return false;


  - name: set_font_bin
    parameters:
      - name: font_bin
        type: AllegroFlare::FontBin*
        default_argument: nullptr
    guards: [ (!built) ]
    body: |
      this->font_bin = font_bin;
      return;


  - name: set_bitmap_bin
    parameters:
      - name: bitmap_bin
        type: AllegroFlare::BitmapBin*
        default_argument: nullptr
    guards: [ (!built) ]
    body: |
      this->bitmap_bin = bitmap_bin;
      return;


  - name: set_event_emitter
    parameters:
      - name: event_emitter
        type: AllegroFlare::EventEmitter*
        default_argument: nullptr
    guards: [ (!built) ]
    body: |
      this->event_emitter = event_emitter;
      return;


  - name: set_entity_collection_helper__this_is_a_hack
    parameters:
      - name: entity_collection_helper__this_is_a_hack
        type: AllegroFlare::Prototypes::FixedRoom2D::EntityCollectionHelper*
        default_argument: nullptr
    guards: [ (!built) ]
    body: |
      this->entity_collection_helper__this_is_a_hack = entity_collection_helper__this_is_a_hack;
      return;


dependencies:


  - symbol: AllegroFlare::InventoryIndex&
    headers: [ AllegroFlare/InventoryIndex.hpp ]
  - symbol: AllegroFlare::Inventory&
    headers: [ AllegroFlare/Inventory.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Entities::Base*>&
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Entities/Base.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Room*>&
    headers: [ map, string, AllegroFlare/Prototypes/FixedRoom2D/Room.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Script>&
    headers: [ map, AllegroFlare/Prototypes/FixedRoom2D/Script.hpp ]
  - symbol: std::map<std::string, std::string>&
    headers: [ map, string ]
  - symbol: AllegroFlare::Inventory*
    headers: [ AllegroFlare/Inventory.hpp ]
  - symbol: AllegroFlare::InventoryIndex*
    headers: [ AllegroFlare/InventoryIndex.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Entities::Base*>*
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Entities/Base.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Room*>*
    headers: [ map, string, AllegroFlare/Prototypes/FixedRoom2D/Room.hpp ]
  - symbol: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Script>*
    headers: [ map, AllegroFlare/Prototypes/FixedRoom2D/Script.hpp ]
  - symbol: std::map<std::string, std::string>*
    headers: [ map, string ]
  - symbol: TheWeepingHouse::EntityFactory
    headers: [ TheWeepingHouse/EntityFactory.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::RoomFactory
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/RoomFactory.hpp ]
  - symbol: AllegroFlare::BitmapBin*
    headers: [ AllegroFlare/BitmapBin.hpp ]
  - symbol: AllegroFlare::EventEmitter*
    headers: [ AllegroFlare/EventEmitter.hpp ]
  - symbol: AllegroFlare::FontBin*
    headers: [ AllegroFlare/FontBin.hpp ]
  - symbol: AllegroFlare::Shader*
    headers: [ AllegroFlare/Shader.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::EntityCollectionHelper*
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/EntityCollectionHelper.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::Configuration
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Configuration.hpp ]


