properties:


  - name: filename
    type: std::string
    init_with: '"filename-not-set.tmj"'
    constructor_arg: true

  - name: num_columns
    type: int
    init_with: 0

  - name: num_rows
    type: int
    init_with: 0

  - name: tile_width
    type: int
    init_with: 0

  - name: tile_height
    type: int
    init_with: 0

  - name: loaded
    type: bool
    init_with: false


functions:


  - name: load
    type: bool
    guards: [ (!loaded) ]
    body: |
      if (!TheWeepingHouse::FileExistenceChecker(filename).exists())
      {
         std::cout << "[TheWeepingHouse::ConfigurationTMJLoader::load]: ERROR: "
                   << "Trying to load the file \"" << filename << "\" but it does not exist."
                   << std::endl;
      }
      return true;
    body_dependency_symbols:
      - std::cout
      - TheWeepingHouse::FileExistenceChecker


  - name: get_num_columns
    type: int
    guards: [ loaded ]
    body: |
      return num_columns;


  - name: get_num_rows
    type: int
    guards: [ loaded ]
    body: |
      return num_rows;


  - name: get_tile_width
    type: int
    guards: [ loaded ]
    body: |
      return tile_width;


  - name: get_tile_height
    type: int
    guards: [ loaded ]
    body: |
      return tile_height;



dependencies:


  - symbol: nlohmann::json
    headers: [ lib/nlohmann/json.hpp ]
  - symbol: TheWeepingHouse::FileExistenceChecker
    headers: [ TheWeepingHouse/FileExistenceChecker.hpp ]


